###########################################################################
###########################################################################
# Get all subscriptions
################
# curl -X 'GET'
#  'http://localhost:9090/api/subscriptions?page=0&pageSize=10'
#  -H 'accept: */*'

#- page: it's the number of the page, where 0 is the first.
#- pageSize is the number of items per page.

GET http://localhost:9090/api/subscriptions?page=0&pageSize=10
accept: */*

###

###########################################################################
###########################################################################
# Create a new subscription
################
# curl -X 'POST'
#  'http://localhost:9090/api/subscriptions'
#  -H 'accept: */*'
#  -H 'Content-Type: application/json'
#  -d '{
#  "id": "string",
#  "email": "string",
#  "firstName": "string",
#  "dateOfBird": "2021-03-25",
#  "gender": "MALE",
#  "newsletterId": "string",
#  "consent": true
#}'

POST http://localhost:9090/api/subscriptions
accept: */*
Content-Type: application/json

{
  "email": "email@mail.com",
  "firstName": "string",
  "dateOfBird": "1970-01-25",
  "gender": "NOT_INDICATE",
  "newsletterId": "string",
  "consent": true
}

###

###########################################################################
###########################################################################
# Get details of a subscription
################
# curl -X 'GET'
#  'http://localhost:9090/api/subscriptions/ID'
#  -H 'accept: */*'
GET http://localhost:9090/api/subscriptions/<ID>
accept: */*

###

###########################################################################
###########################################################################
# Cancel existing subscription
################
# curl -X 'DELETE'
#  'http://localhost:9090/api/subscriptions/ID'
#  -H 'accept: */*'
DELETE http://localhost:9090/api/subscriptions/<ID>
accept: */*

###


